# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wemucs
email: che.camus@gmail.com
description: > # Il était une fois les globe-trotteurs du Web...
    Un journal d'aventures, de découvertes, de déconvenues et de leçons apprises sur les chemins 2.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wemucs.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

repository: wemucs/wemucs.github.io

# Build settings
markdown: kramdown
theme: minima

collections:
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/
  my_authors:
    output: true
    permalink: /author/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Outputting
permalink: /post/:title/
paginate: 10
paginate_path: '/page/:num/'
timezone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: my_authors
    values:
      layout: author
